### PR TITLE
Add a status filter to the "Toezicht" overview page

### PR DESCRIPTION
**Pull request by Windvis**
This makes it (a little) easier to find the submission we want.

image

Builds on #398

### CODE REVIEW

**Comment by Windvis** [comment]
(Moving it back to draft since we might want to add more filters? Needs to be discussed further)

**Comment by benjay10** [comment]
As already mentioned by Riad, the menu indeed does not close after selecting an option. You can only select a single option, so the menu can be closed immediately after selecting one.

**Comment by Windvis** [comment]
> As already mentioned by Riad, the menu indeed does not close after selecting an option. You can only select a single option, so the menu can be closed immediately after selecting one.

Thanks, should be good now :+1:

**Comment by benjay10** [comment]
Yes, seems fixed now.

**Review by Riadabd — APPROVED** [review]
Looks good now :+1:

**Pull request merged**
