### PR TITLE
Bump appuniversum to 0.4.3 (needed for the accordion component)

### PR DESCRIPTION
**Pull request by aatauil**
- Needed for the new accordion component and just needed a bump in general

### CODE REVIEW

**Comment by Windvis** [comment]
There was a breaking change in the 0.4.0 release which needs to be handled I think:

 `<AuLoader @size>` was renamed to `@padding`.

https://appuniversum.github.io/ember-appuniversum/docs/atoms/au-loader

**Comment by Windvis** [comment]
I think the new date picker also uses a different format by default so it probably requires updating the labels, or configure the datepicker.

**Comment by aatauil** [comment]
@

> There was a breaking change in the 0.4.0 release which needs to be handled I think:
> 
> `<AuLoader @size>` was renamed to `@padding`.
> 
> https://appuniversum.github.io/ember-appuniversum/docs/atoms/au-loader

Not quite a "breaking" change as it is an easthetic thing but definitly something that should be dealt with. Actually missed that when going through the commits so good catch! Thanks you, should be ready to merge :)

**Comment by Windvis** [comment]
I only know because I received the same feedback in GN :smile:. The appuniversum repo could really use a changelog to be honest.

**Review by Windvis — APPROVED** [review]

**Comment by aatauil** [comment]
Yeah changelog or at least put a description on what changed when releasing (in the notes) since now it just says something like "release v1.0.0" . I will actually open an issue for it since upgrading would be much easier

**Pull request merged**
