### PR TITLE
Allow users to link an instance to a concept

### PR DESCRIPTION
**Pull request by Windvis**
~~This targets #296 so that needs to be reviewed and merged first.~~ Done

### CODE REVIEW

**Comment by benjay10** [comment]
I encountered some problems.

When trying to link the instance to a concept, we get a data table with "Koppelen" actions and a cancel button. Clicking "Koppelen" works, so that's good.

If instead you click a concepts to figure out if it fits, you only see "Voeg toe" which creates an entirely new instance from it.

If you navigate back to the concept list using the "Bekijk andere concepten" navigation link, you loose the "Koppelen" mode completely and you can only add new instances. You have to go back to the catalogue and edit the instance again.

**Comment by benjay10** [comment]
Also, maybe not related to this PR, I constantly get `Uncaught (in promise) TypeError: this.formStore is undefined` errors when clicking around too quickly.

E.g. in the catalogue, edit an instance and click on the "Terug naar overzicht" button immediately. It also happens when clicking on the "Koppelen" button. When you wait for the page to load first, there are no errors.

**Comment by Windvis** [comment]
> If instead you click a concepts to figure out if it fits, you only see "Voeg toe" which creates an entirely new instance from it.

Oh, right, I totally forgot about that part 😅, thanks.

> Also, maybe not related to this PR, I constantly get Uncaught (in promise) TypeError: this.formStore is undefined errors when clicking around too quickly.

Yea, I noticed that as well. It happens if you exit the route before the form is fully loaded. The willDestroy method needs some extra safety checks. I was planning to fix it in a standalone PR.

**Comment by Windvis** [comment]
> I encountered some problems.
> 
> When trying to link the instance to a concept, we get a data table with "Koppelen" actions and a cancel button. Clicking "Koppelen" works, so that's good.
> 
> If instead you click a concepts to figure out if it fits, you only see "Voeg toe" which creates an entirely new instance from it.
> 
> If you navigate back to the concept list using the "Bekijk andere concepten" navigation link, you loose the "Koppelen" mode completely and you can only add new instances. You have to go back to the catalogue and edit the instance again.

I added this part of the feature now as well 👍.

**Review by benjay10 — APPROVED** [review]
Yes seems to work better now!
"Koppelen" keeps working in the multiple different locations.

**Pull request merged**
