### PR TITLE
Update ember-concurrency to v2

### PR DESCRIPTION
**Pull request by Windvis**
This PR updates ember-concurrency to v2 and also replaces all the older task syntax with "real" decorators in native classes.

Once this is merged, the project can be configured to use Prettier, which will solve a lot of styling related issues (like missing semicolons). Normally that setup is part of the 3.24 update, but it can be set up manually to get the benefits without having to update.

### CODE REVIEW

**Comment by Windvis** [comment]
I'll rebase once #41 is merged since that adds new code with ember-concurrency-decorators decorators.

**Review by claire-lovisa — APPROVED** [review]
Tested an approved :) can be merged to dev once #41 is merged !

**Comment by Windvis** [comment]
@claire-lovisa I rebased this PR on development to fix the merge conflicts. I think it might make more sense to merge this one first and update the other PR after that. I need to do some other changes in there anyway. :smile:

**Comment by claire-lovisa** [comment]
@Windvis Ok ! Perfect then :)

**Pull request merged**
